version: '3'

services:
  swarm01:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    ports:
      - "51010:51010"
      - "8080:8080"
    environment:
      SWARM_NAME: ${NODE_NAME}
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://testnet-infra.bluzelle.com/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
      STATSD_COLLECTOR: ${STATSD_COLLECTOR}
    expose:
      - "51010"
      - "8080"
    volumes:
      -  ${SWARM_HOME}:/opt/bluzelle/swarm_home
    restart: on-failure

  signalfx:
      image: quay.io/signalfx/signalfx-agent:4.5.0
      environment:
        - SFX_ACCESS_TOKEN=${SFX_TOKEN}
        - SFX_INGEST_URL=https://ingest.us1.signalfx.com
        - COLLECTD_HOSTNAME=amastracci-blz
      volumes:
        - /:/hostfs:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/bluzelle/signalfx/:/etc/signalfx/:ro
      expose:
        - "8125/udp"

