version: '3'

services:
  REPLACE_DOCKER_STACK:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://13.57.242.214:12201
        tag: "testnet"
    ports:
      - "51010:51010"
      - "12201:12201"
    environment:
      SWARM_NAME: node_0_SWARM_NAME_REPLACE
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://testnet-infra.bluzelle.com/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
      STATSD_COLLECTOR: "signalfx"
      NUM_NODES: 1
    ulimits:
      core:
        soft: 99999999999
        hard: 99999999999
    security_opt:
      - seccomp:unconfined
    expose:
      - "51010"
    volumes:
      -  ${SWARM_HOME}:/opt/bluzelle/swarm_home
      - /tmp/cores:/tmp/cores
    restart: on-failure

  # signalfx:
  #     image: quay.io/signalfx/signalfx-agent:4.5.0
  #     environment:
  #       - SFX_ACCESS_TOKEN=REPLACE_SFX_TOKEN
  #       - SFX_INGEST_URL=https://ingest.us1.signalfx.com
  #       - COLLECTD_HOSTNAME=amastracci-blz
  #     volumes:
  #       - /:/hostfs:ro
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - /opt/bluzelle/signalfx/:/etc/signalfx/:ro
  #     expose:
  #       - "8125/udp"

