version: '3'

services:
  swarm_node:
    image: bluzelle/swarmdb:latest
    ports:
      - "51010:51010"
      - "8080:8080"
    environment:
      SWARM_UUID: "${SWARM_UUID}"
      SWARM_NAME: "${SWARM_NAME}"
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "${SWARM_BOOTSTRAP_URL}"
      NODE_DEBUG_LOGGING: "true"
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
      MONITOR_ADDRESS: "monitor.bluzelle.com"
    expose:
      - "51010"
      - "8080"
    volumes:
      - /tmp:/tmp/swarm_home
    restart: on-failure:5

  datadog:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=${DATADOG_API_KEY}
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - "8125:8125/udp"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

