version: '3'

services:
  REPLACE_DOCKER_STACK:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "150m"
    #     max-file: "3"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "testnet"
    depends_on:
      - logstash
    ports:
      - "51010:51010"
    environment:
      SWARM_NAME: node_0_SWARM_NAME_REPLACE
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://testnet-infra.bluzelle.com/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
      STATSD_COLLECTOR: "signalfx"
      NUM_NODES: 1
    ulimits:
      core:
        soft: 99999999999
        hard: 99999999999
    security_opt:
      - seccomp:unconfined
    expose:
      - "51010"
    volumes:
      -  ${SWARM_HOME}:/opt/bluzelle/swarm_home
      - /tmp/cores:/tmp/cores
    restart: on-failure

  # ELK STACK
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      - "xpack.monitoring.elasticsearch.url=http://ELASTIC_URL:9200"
    volumes:
      - .:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/ --config.reload.automatic
    expose:
      - "12201/udp"
      - "5044"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://ELASTIC_URL:9200
      XPACK_SECURITY_ENABLED: "false"
    depends_on:
      - elasticsearch
    expose:
      - "5601"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - "xpack.security.enabled=false"
    expose:
      - "9200"

  signalfx:
      image: quay.io/signalfx/signalfx-agent:4.5.0
      logging:
        driver: "json-file"
        options:
          max-size: "150m"
          max-file: "3"
      environment:
        - SFX_ACCESS_TOKEN=REPLACE_SFX_TOKEN
        - SFX_INGEST_URL=https://ingest.us1.signalfx.com
        - COLLECTD_HOSTNAME=amastracci-blz
      volumes:
        - /:/hostfs:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/bluzelle/signalfx/:/etc/signalfx/:ro
      expose:
        - "8125/udp"

