services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "kbR4VBpfRdiAOM3ZDdlNLBqwP8+bXSIjkfQvGCejnhi5/PbRugm4+VnX1a8NLmzaGt7X2MJUIF3B/Auy7HzrLmNSI+6iVmqryTxn8sLgQ8OpO+FT7+TLmMvq3eJ3WQHO9qicjxeUGjhslTRMR1MFHu65SOYAncvVbf4V9WEy9OPC/Bt+EYHwYvLLO5nLSnOawvVcRWoTOqNrgQfu46gax1kTSbWSdnod3IZ4QyrWZgehbjxc8Lo7gGjRBXtEtpzU15GqRVzYLdvOs4hlrQlThqmrAoBGz8kRSS8KoePYhEIaUiWMjH+8JqPE5i6B4FQmRvPkyfElTiGAoXB1Kh+WwoUvmxcHahsdkmZ2y59azwoe2eF0dsiDCPL3Hp4acNCfsmLn+h8sFf8xHDY2kR61rsMUvcCAOUmWn/fz1R1lxd6uGQQTAVlQJlNbufic12UZG0XinxwiTs6VxM4Y43WlGO8LCJ5NKdTBEH+/HHAqcyESJtER6tUK2bpHH7V3PnpPh9JZhiYAd51uC0sApVs3BW8/P1YDVnjW9rIY4gg1I2J9NEVtX9o12HGv0Q/5DaJPLn035U8mWF6vfP2X4WtetFpnTNwJ884b2vGWbv+4hJnZk4FcbNbNZWQw8wMPkRoorYanM2e+NdhLznS5gmGrJ0uEUW1LMgCXOXysxSdbv/c="
    - secure: "TonBJRPZOAB9Yt2f7935gQfRGcsNdOz5Boj1OF3Xg5cChFI9DKnqwRrnF19zQ0JXpKwbhDvofmSStGL56u2J+BzraYQT0+8QMDcIwxQPeO74+vMgg7MKgjCVCqdgCIpnvDpCMj0mo83odaa8peZJfvJ7KkrWDDj33v/zhO0WOx06Klxq01xJ2K0kib9Lu0JM2tWc0//m9aaVv8Yq4CJhhzQYxjjg/reclBB6s0Op5/PKetL3nzTKpQ5QmKilHK4FtUbwMHkSsMOYsGD1JpATbuBCNLGSuEVThchSAawggeeQ67Usp7bcMxOaoRaipxitfJj8NUSNDfqg0vpVybRE8gVvPmpzgxKnZuqWmD0Vuqo6asKo7gZ9mJI9NCkBtxjaNi0H5VPta2LXGxjJVbRwhhQJowmpTm2j/0tCeDw5S+3QLo1X/65jDtvu/nWgX6GQzcbCJDwz0JPCGOWUKZZt9dbcKbsvVzfMFK8nXlpY3Qs7Wn12blJ+B4r5jhiDqwQYCJbefcmt6OkZsAwInYavIbB1rPW4mis0/fMELng7VHBb40jK6E1ZB5HUy2B7flu0C0cUkcY3BXKmrjqb7EF3BY70pt2XSATQOX2btwRk2E0ajfUsPs/m2/9Py0LGmp/1xEpUraXp1pBp2UES16eO6dikeUxrLB4V66kOE3gvps8="

  matrix:
    - REPO=bluzelle/swarmdb           DOCKERFILE_DIR=swarm-node
    - REPO=bluzelle/peerlist-server   DOCKERFILE_DIR=peerlist-server

before_install:
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"

script:
  - export DEBIAN_COMPONENT=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "stable"; else echo "unstable"; fi`
  - cd ${DOCKERFILE_DIR}
  - docker build --build-arg DEBIAN_COMPONENT=$DEBIAN_COMPONENT -t ${REPO}:${COMMIT} .

after_success:
  - export TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH}; fi`
  - docker tag ${REPO}:${COMMIT} ${REPO}:${TAG}
  - docker tag ${REPO}:${COMMIT} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}
  - docker push ${REPO}
