version: '3'

services:
  swarm01:
    image: bluzelle/swarmdb:travis-53
    ports:
      - "51010:51010"
      - "8080:8080"
    environment:
      SWARM_UUID: "92b8bac6-3242-452a-9090-1aa48afd71a3"
      SWARM_NAME: "swarm01"
      SWARM_PORT: "51010"
      HTTP_PORT: "8080"
      SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
    expose:
      - "51010"
      - "8080"
    networks:
      - swarmnet
    volumes:
      - /tmp:/tmp/swarm_home
    depends_on:
      - "peers-server"
      
  swarm02:
    image: bluzelle/swarmdb:travis-53
    ports:
      - "51011:51010"
      - "8081:8081"
    environment:
      SWARM_UUID: "c864516b-3c95-4721-ad3e-a8dccd0d8349"
      SWARM_NAME: "swarm02"
      SWARM_PORT: "51010"
      HTTP_PORT: "8080"
      SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
    expose:
      - "51011"
      - "8081"  
    networks:
      - swarmnet
    volumes:
      - /tmp:/tmp/swarm_home
    depends_on:
      - "peers-server"

  swarm03:
      image: bluzelle/swarmdb:travis-53
      ports:
        - "51012:51010"
        - "8082:8082"
      environment:
        SWARM_UUID: "137a8403-52ec-43b7-8083-91391d4c5e67"
        SWARM_NAME: "swarm03"
        SWARM_PORT: "51010"
        HTTP_PORT: "8080"
        SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
        NODE_DEBUG_LOGGING: "true"
        LOCAL_IP: ${LOCAL_IP}
        ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
        ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
      expose:
        - "51012"
        - "8082"
      networks:
        - swarmnet
      volumes:
        - /tmp:/tmp/swarm_home
      depends_on:
        - "peers-server"

  peers-server:
    image: bluzelle/peerlist-server
    ports:
      - "80:8080"
    environment:
      LOCAL_IP: ${LOCAL_IP}
    expose:
      - "8080"

networks:
  swarmnet:
    driver: bridge
