version: '3'

services:
  swarm01:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    ports:
      - "51010:51010"
      - "8080:8080"
    environment:
      SWARM_NAME: "node_0"
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
    expose:
      - "51010"
      - "8080"
    networks:
      - swarmnet
    volumes:
      -  ${SWARM_HOME}:/opt/bluzelle/swarm_home
    depends_on:
      - "peers-server"
    restart: on-failure

      
  swarm02:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    ports:
      - "51011:51011"
      - "8081:8081"
    environment:
      SWARM_NAME: "node_1"
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
    expose:
      - "51011"
      - "8081"  
    networks:
      - swarmnet
    volumes:
      - ${SWARM_HOME}:/opt/bluzelle/swarm_home
    depends_on:
      - "peers-server"
    restart: on-failure

  swarm03:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    ports:
      - "51012:51012"
      - "8082:8082"
    environment:
      SWARM_NAME: "node_2"
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://${LOCAL_IP}/peerlist.json"
      NODE_DEBUG_LOGGING: "true"
      LOCAL_IP: ${LOCAL_IP}
      ETHEREUM_ADDRESS: ${ETHEREUM_ADDRESS}
      ETHEREUM_IO_API_TOKEN: ${ETHEREUM_IO_API_TOKEN}
    expose:
      - "51012"
      - "8082"
    networks:
      - swarmnet
    volumes:
      - ${SWARM_HOME}:/opt/bluzelle/swarm_home
    depends_on:
      - "peers-server"
    restart: on-failure

  graphite:
      image: graphiteapp/graphite-statsd
      ports:
        - "8125:8125/udp"
        - "28080:80"
      expose:
        - "8125/udp"
        - "28080"
      networks:
        - swarmnet
      volumes:
        - /tmp:/tmp/swarm_home

  peers-server:
    image: bluzelle/peerlist-server:desk
    ports:
      - "80:8080"
    environment:
      LOCAL_IP: ${LOCAL_IP}
    expose:
      - "8080"
    volumes:
      - ${SWARM_HOME}:/opt/bluzelle/swarm_home
    restart: on-failure

networks:
  swarmnet:
    driver: bridge
