version: '3'

services:

  peers-server:
    image: bluzelle/swarmdb:${SWARMDB_TAG}
    ports:
      - "80:8080"
    environment:
      LOCAL_IP: ${LOCAL_IP}
    expose:
      - "8080"
    volumes:
      - ${SWARM_HOME}:/opt/bluzelle/swarm_home
    restart: on-failure

networks:
  swarmnet:
    driver: bridge
